updated docker settings

diff --git a/backend/project_novel/dockerfile b/backend/project_novel/dockerfile
--- a/backend/project_novel/dockerfile
+++ b/backend/project_novel/dockerfile
@@ -5,12 +5,6 @@ FROM python:3.11.5-alpine3.18
 ENV PYTHONDONTWRITEBYTECODE 1
 ENV PYTHONUNBUFFERED 1
 
-# Receive ARG as build-time variable
-ARG DJANGO_SECRET_KEY
-
-# Set environment variable from ARG
-ENV DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
-
 # Set work directory
 WORKDIR /app
 
@@ -24,11 +18,11 @@ RUN pip install --upgrade pip && pip install -r requirements.txt
 # Copy project files into the docker image
 COPY . /app/
 
-# Check if gunicorn is in requirements.txt
-RUN if ! pip show gunicorn > /dev/null; then \
-        echo "gunicorn not found in requirements.txt"; \
-        exit 1; \
-    fi
+# # Check if gunicorn is in requirements.txt
+# RUN if ! pip show gunicorn > /dev/null; then \
+#         echo "gunicorn not found in requirements.txt"; \
+#         exit 1; \
+#     fi
 
 # Collect static files
-RUN python manage.py collectstatic --noinput
+# RUN python manage.py collectstatic --noinput
